import os

import pytest
from helpers.test_connection import TestConnection
from helpers.test_fixtures import test_datasource

# define environment variables used in test cases
TRINO_HOST = os.getenv("TRINO_HOST", "")
TRINO_PORT = os.getenv("TRINO_PORT", "")
TRINO_USERNAME = os.getenv("TRINO_USERNAME", "")
TRINO_PASSWORD = os.getenv("TRINO_PASSWORD", "")
TRINO_CATALOG = os.getenv("TRINO_CATALOG", "")

# unsecured JWT token generated by https://jwt.io/ with header { "alg": "none" } and payload {}
FAKE_JWT_TOKEN = "eyJhbGciOiJub25lIn0.e30."

from unittest.mock import Mock
                                                                                                                    
def mock_requests_post(token_url: str, data: dict) -> dict:
    response = Mock()
    response.status_code = 200
    response.json.return_value = {"access_token": FAKE_JWT_TOKEN}    
    return response


# define test cases and expected behavior (passing unless otherwise specified)
test_connections: list[TestConnection] = [
    TestConnection(  # correct connection, should work
        test_name="correct_username_password",
        connection_yaml_str=f"""
                type: trino
                name: TRINO_TEST_DS
                connection:
                    host: '{TRINO_HOST}'
                    port: '{TRINO_PORT}'
                    user: '{TRINO_USERNAME}'
                    password: '{TRINO_PASSWORD}'
                    catalog: '{TRINO_CATALOG}'
            """,
    ),
    TestConnection(  # correct connection, should work
        test_name="auth_type_username_password",
        connection_yaml_str=f"""
                type: trino
                name: TRINO_TEST_DS
                connection:
                    host: '{TRINO_HOST}'
                    port: '{TRINO_PORT}'
                    user: '{TRINO_USERNAME}'
                    password: '{TRINO_PASSWORD}'
                    catalog: '{TRINO_CATALOG}'
                    auth_type: 'BasicAuthentication'
            """,
    ),    
    TestConnection(  # bad connection params
        test_name="auth_type_username_password_missing",
        valid_yaml=False,
        expected_yaml_error="password\n  Field required [type=missing,",
        connection_yaml_str=f"""
                type: trino
                name: TRINO_TEST_DS
                connection:
                    host: '{TRINO_HOST}'
                    port: '{TRINO_PORT}'
                    user: '{TRINO_USERNAME}'
                    catalog: '{TRINO_CATALOG}'                    
            """,
    ),
    TestConnection(  # correct connection, should work
        test_name="correct_username_password_with_options",
        connection_yaml_str=f"""
                type: trino
                name: TRINO_TEST_DS
                connection:
                    host: '{TRINO_HOST}'
                    port: '{TRINO_PORT}'
                    user: '{TRINO_USERNAME}'
                    password: '{TRINO_PASSWORD}'
                    catalog: '{TRINO_CATALOG}'
                    http_scheme: 'https'
                    http_headers:                        
                    source: 'soda-core'
                    client_tags:
                        - 'soda-core'
            """,
    ),
    TestConnection(  # fake unsecured token, will connect but fail at query stage
        test_name="jwt_auth",
        connection_yaml_str=f"""
                type: trino
                name: TRINO_TEST_DS
                connection:
                    host: '{TRINO_HOST}'
                    port: '{TRINO_PORT}'
                    catalog: '{TRINO_CATALOG}'
                    auth_type: 'JWTAuthentication'
                    access_token: '{FAKE_JWT_TOKEN}'
            """,
        query_should_succeed=False,
        expected_query_error="disallowed",                
    ),
    TestConnection(  # fake unsecured token, will connect but fail at query stage
        test_name="oauth",
        connection_yaml_str=f"""
                type: trino
                name: TRINO_TEST_DS
                connection:
                    host: '{TRINO_HOST}'
                    port: '{TRINO_PORT}'
                    catalog: '{TRINO_CATALOG}'
                    auth_type: 'OAuth2ClientCredentialsAuthentication'
                    oauth: 
                        token_url: 'https://example.com/token'
                        client_id: 'client_id'
                        client_secret: 'client_secret'
            """,
        query_should_succeed=False,
        expected_query_error="disallowed",                
        monkeypatches={"requests.post": mock_requests_post},
    ),
    TestConnection(  # fake unsecured token, will connect but fail at query stage
        test_name="oauth_extra_params",
        connection_yaml_str=f"""
                type: trino
                name: TRINO_TEST_DS
                connection:
                    host: '{TRINO_HOST}'
                    port: '{TRINO_PORT}'
                    catalog: '{TRINO_CATALOG}'
                    auth_type: 'OAuth2ClientCredentialsAuthentication'
                    oauth: 
                        token_url: 'https://example.com/token'
                        client_id: 'client_id'
                        client_secret: 'client_secret'
                        scope: 'scope1 scope2'
                        grant_type: 'grant_type'
            """,
        query_should_succeed=False,
        expected_query_error="disallowed",                
        monkeypatches={"requests.post": mock_requests_post},
    ),
]


# run tests.  parameterization means each test case will show up as an individual test
@pytest.mark.skipif(test_datasource != "trino", reason="Only test for Trino")
@pytest.mark.parametrize("test_connection", test_connections, ids=[tc.test_name for tc in test_connections])
def test_trino_connections(test_connection: TestConnection, monkeypatch: pytest.MonkeyPatch):
    test_connection.test(monkeypatch=monkeypatch)
